### ISSUE TITLE
Decide what's going to happen to this repo

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-nbt#4]
Situation : 
* @roblabla would like to stop parsing nbt in https://github.com/PrismarineJS/node-minecraft-protocol
* https://github.com/sjmulder/nbt-js doesn't seem to be maintained anymore (see https://github.com/sjmulder/nbt-js/issues/10)
* even if the changes on this repo were done for node-minecraft-protocol particular cases, they might still be useful in general
* https://github.com/wtfaremyinitials/minecraft-schematic is now using prismarine-nbt
* nbt parsing/writing is useful in mineflayer anyway

Problems : 
* this repo has no documentation
* the original nbt.js repo has no documentation either

Which repo should be updated ? Is prismarine-nbt going to be PR'd back to nbt.js or should we continue here ?

**Comment by roblabla** [comment]
We should continue here, I guess, if minecraft-schematic uses prismarine's nbt parser. Besides, mineflayer probably should expose a high-level API for the NBT, and probably should base it off this repo as well. There are a number of things we absolutely need to do though, if we're going down that road : 

1. Document this repository. This is fairly easy to do.
2. Create a function that allows to "flatten" the parsed JSON down to something more akin to what nbt.js produces. The parser currently gives you a very weird structure like { type: "string", value: "test" }, instead of just "test", and that gets even worse in hierarchical structures.

**Comment by sjmulder** [comment]
HI guys,

I'm flattered to see that the library has found use and ashamed that it's gone unmaintained by me for so long. I had a masive career change and just haven't been able to focus on coding at all for the past year.

The improvements here are tremendous. I've taking the liberty of merging the changes back into [NBT.js](https://github.com/sjmulder/nbt-js). Apart from some formatting changes and small refactoring, I've made the writer a bit more flexible by adding seeking backwards and forward without destroying data. I've also added some documentation in the form of a changelog and an updated readme.

My own plans for NBT.js are as follolws:

1. Migrate to newer JavaScript syntax for less crud and more clarity. Also more rigorous linting/static analysis. It's JavaScript after all.
2. Browser support.

As for maintainership: it feels wasteful to me to have these two projects exist in parallel. prismarine-nbt, of course, exists to address a specific need for the Prismarine project. I'd happily incorporate any improvements for the benefit of that; then meanwhile you can benefit from general improvements to NBT.js. I'd happily give commit access too.

If you'd rather stick with your own repo for whatever reason - even if just to keep all the libs here together - then that's fine to of course. Might be worth checking out my patches and merging them back.

**Comment by roblabla** [comment]
As a general rule, I'd actually rather use an existing library instead of using our own (for instance,  we are now using node-yggdrasil package for auth). The reason I didn't pr the prismarine-nbt changes back upstream was because the changes are fairly invasive, and I wasn't sure they would be useful or welcome. 

The main thing I need out of the nbt lib in nmp is a way to reserialize the nbt perfectly.  This means the deserialized json needs to know about the different number types.

I'll check out the nbt.js update.

**Comment by roblabla** [comment]
Oh wow,  just looked at the repo and realized you also added the type info to the returned hash.  That's cool. I'll try to make nmp use nbt.js this weekend.

**Comment by sjmulder** [comment]
Yeah I realised that it made a lot of sense given that you need the type info for writing anyway. Also, I initiially made `parseUncompressed()` return a POD object again but there the consistent name/value structure as you did it is better so I've reverted to that in 0.6.

> The main thing I need out of the nbt lib in nmp is a way to reserialize the nbt perfectly

Added a test to validate this in 0.6 [in nbt-spec.js](https://github.com/sjmulder/nbt-js/blob/a44541fe408d69ec5ead512027e35ad39e1e9799/test/nbt-spec.js#L71).

**Comment by rom1504** [comment]
I ended up completely reimplementing this lib using our new serializer/parser lib https://github.com/roblabla/ProtoDef . I think the end result is cleaner.
But it's really a totally different implementation now so I think it wouldn't make much sense merging into nbt.js at this point.
